### ISSUE TITLE
Use special double entries in gdextension

### ISSUE THREAD

**Issue by fire** [godotengine/godot-cpp-template#62]
### Godot version

https://github.com/V-Sekai/godot/commit/35b10e36d919247cf9e7c06892bf1c38ef027b0b

### godot-cpp version

https://github.com/godotengine/godot-cpp/tree/fbbf9ec4efd8f1055d00edb8d926eef8ba4c2cce

### System information

Macos

### Issue description

Godot added a feature for the particular naming of the double extension libraries.

https://github.com/libriscv/godot-sandbox/blob/main/bin/addons/godot_sandbox/bin/godot-riscv.gdextension

godot-cpp-template does not use it. https://github.com/godotengine/godot-cpp-template/blob/main/demo/bin/example.gdextension

godot-cpp-template should use the special syntax. Note that the order of the double vs single matters.

**Comment by Ivorforce** [comment]
This is half addressed in #55, through the use of `env["suffix"]` in the naming scheme, which is [defined here](https://github.com/godotengine/godot-cpp/blob/253e095c815158184c9ec044fd0699d93c68675d/tools/godotcpp.py#L495) and (i think) intended for this purpose. The PR does not currently add new entries to the .gdextension file.

**Comment by fire** [comment]
I downloaded 
![image](https://github.com/user-attachments/assets/7448b5c6-e739-4367-b196-637908c5a0c1)
 from https://github.com/godotengine/godot-cpp-template/actions/runs/11691017198/job/32557244884 doubles build.

godot-cpp-template.zip and it does not build doubles `libEXTENSION-NAME.macos.template_debug`, I suspect it is overwriting.

Secondly `libEXTENSION-NAME.macos.template_debug` is missing env["arch"]

**Comment by Ivorforce** [comment]
> Secondly `libEXTENSION-NAME.macos.template_debug` is missing env["arch"]

That one _is_ actually fixed by #55.

**Comment by unvermuthet** [comment]
With #77 the `double` binaries for macOS and iOS are now present but they're still not referenced by the .gdextension file.
